[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "f6198d2a83ddc3ee96e3e0043e2722d2f3a779e5"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "f7f7e413f8b760ca62d60a02e74d267274240aff2ce6046f99ddc00282243873"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.aarch64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "b61c1baf1efafca4094e3cc57ace883e33fd23f7"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "503415f0c9d8e5a5a8e8d3e36bc904076c0e41dc466b6d9ea37390af507fc988"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.aarch64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "aaaf11cdcd9322c568f4292dc55da403b136956c"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "7986dfe009cbd9a3ab1a6a2a28fef8b738e9f1604f76f20d199901a0d39a0636"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.aarch64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "78933bb535efeb816218bab7bdfaca08d1189e4e"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "67c60ffc30dbb98ec51bd57239c9da48072870afa3e4d18ec3f1d3668ed141c0"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.aarch64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8b30d1864a0f29681906ce57663c31f6646cee8"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "0d0117c6e1dc290bfd52dd7d419007a79202048667f6720912ca78a169e5e65e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62ae369b40504f732434e4e371a67e593448545b"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "b2f84d62fc8eb1ec4b709e2cb0f15ac223069d9c7cb04c980673773fd61041dc"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.armv6l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98ac539374b1d25752bc7e13e89e69a3efbe5992"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "bdd208d2ea8cbac6dfe4188283e5d1e7e991494fe91353036a1a942ad2c3a2e1"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1196f715dc747ef243cdcf5879ec40ec15564547"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "c6ad00768aa83e846e762072660f80900634fbcbf7d4d904e444176ad563e296"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.armv7l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "d15229c85db36633444fad74bd98b7dcc58e5bbe"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "6d25c556e1bbb9e52fd98e168c45c7259a537064cb8701feb4c16ea1f57e7c66"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.i686-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "b240911108572f5d20dbe291cc9b8f7be59f1916"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "8a2f86f016124cb2e0dbe8825b95bce908fa93a80a5904aacdd81b25124b2f8b"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.i686-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "powerpc64le"
git-tree-sha1 = "7c0232e5cc2fa03e3e19c88d53c48f00b2a63db5"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "8ed63c51b5345f0ce7077d1a1bc03b71df24ce421a5a8e26dce98a447ab96e79"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.powerpc64le-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "riscv64"
git-tree-sha1 = "f2108ad11b0bc0f8c9ede665dc18614b703d4cfe"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "ef2e976bf1ba11b82185d0f204b6b791d53594192ff39d035fff5565d9e3f551"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.riscv64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "292028ea5e39446425a2eb700bedd1ed98fd0021"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "dd6cf2f79cfe0d835abdf298ccce8808583adceaf2e9a83dccf89d90604ecb41"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.x86_64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "3805b77c67607622baf7a3f683b70d35ca87e6f4"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "97b822030c8bbaf5b4a80ca1a4451e088a65f7535a450165756a5f920c44eddd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.x86_64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "0a45a8f69c5ee555c6e76128dae23bc2456cef0d"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "151d35b07055fb8f0cf7eabf41670b454fe2a2071df963916df001aff76e5abb"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.x86_64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "e49805c15d8114fb8697b66b9df75fb28e5f0b38"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "e66dd6e0ab400c40ec0c599b8f57d1e2a5402cf5c1c9eb73064ffaff670c666d"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "b5c3d319e357107b5dead8cecfaa6967fd436661"
os = "windows"

    [[aws_c_mqtt.download]]
    sha256 = "107baf7118eb878cc7d8e6187bdf6189e7168ffc36affd321439c38bffe7bb3c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.14.0+0/aws_c_mqtt.v0.14.0.x86_64-w64-mingw32.tar.gz"
