[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "715cc7bf1cf3b50527157983478a9fdab24d2c84"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "4676de168a4f7328e882ba37d2f43c6394d32d21dfe4abca84222fa672acf686"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.aarch64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "ccd86fed8eab25e00144abc6b62d1fd12e2e7193"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "b24e8a69aad9bb24c95a1d9073acd80d91d012e0d1b800c917a4af72777d5c65"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.aarch64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "76b27433a6b2189396b4391c5fd706ef1830210c"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "b00ee09d71343e2f46d9f85ad08af11116b36860aeb9036479a12210c76df069"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.aarch64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "5686c0d094e1b33e9dd587af040641b95e3ee41f"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "671c491c5ca4091ebd94171dabd4042432b1354ceb2220473262e4c8292f6a43"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.aarch64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8639950a8f08526366ae67f5399bfb2361fd394"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "66ac44f866552fa981e2398f81e180564331324b92ff28177e53b82616b7fc58"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a624791f264418ad8fe023a51c6fc5eaad73668c"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "378d54dbd1069de8f9ba3a1b73f04299dfbe6dd11b30f12463ac2644aa653aec"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.armv6l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77c76a4394d50ad74c2885bbb07b417151af69fa"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "6123250b01d379a166ea9cc579e5aa6fa35216d5ab881f7a0543fbabda6f225c"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cfcee33b2ca02bb75a66e2b45dd8f92b411193b8"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "8cc85e32173477f74c5b8534595e239f0a02cfc5fac1d09de4bc77a74c1d8f49"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.armv7l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "d62992fb591c085b320a8fb54f454ebb4ff73d77"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "211d86379d6c06b05f06ffe64eee263f5441462637628826428f200c7bd784e2"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.i686-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "326baa5f4ba51b52957cc842fe9868ef6f62991c"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "58929ab654b4dca88403b1ebd734519609d1946077a16cd8bfc756d310a0a2ab"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.i686-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "powerpc64le"
git-tree-sha1 = "4723baf6c98d9c05d1551f3569d023303886043e"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "36e89c61275d31fd1cd86c97c28ae7623129cbf290ccd7864a0c4fd37f6754fd"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.powerpc64le-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "riscv64"
git-tree-sha1 = "66fcb889d5f71948bfe92aeec06354e3f109b70f"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "af2967d8952af53a481ed7f756ed1f6264a40649ee45e0c9d35ed33062a49184"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.riscv64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "80a4a9113fbead94d45295f70ac942916409776b"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "c2081a2519737b1a60ba4fa9f23387064baab7315a7e777eeb2d95bc4f82874f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.x86_64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "109a7e16d7afdf304df852a4f596cd2d348a7db9"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "804e595d6d9c2cb574d3546dd219f078ac5d83b430ee714c28338aabd6da6d09"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.x86_64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "d1010cff967405b4a330ad77aa6f259a0029c154"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "4392a7feb6d23866b76ff9217bf3cf653ef170faf23f6fffcfbec0117ad9090a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.x86_64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "1399411654eac5f29de38f56cf13d2aafaa09cd0"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "59e67f72e7dff44d5a2bd7393668b1d79d51decbe76addd8662d1bfc71cc9619"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.x86_64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "59ee459ad2a1aff58f90a1a65bff1c58c46e8552"
os = "windows"

    [[aws_c_mqtt.download]]
    sha256 = "489ff75f05d6f697f17d9f7a345deeeb25b71ec58274329b6e3980c8784b83ff"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.3+0/aws_c_mqtt.v0.13.3.x86_64-w64-mingw32.tar.gz"
