[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "3c029bc4bf722c9bf37ccd341a468ebd66981aca"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "25e9238bd8a74a81519343297b3a51cd80ac260615a0143b9d59c7a4f9053a30"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.aarch64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "a2efd3903961e4a4802726f9434cdb5e041e6ca4"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "065631c4ba64b90662d065cc78b6ac1f089e4a739017c3b0ef14f4f704c90e9a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.aarch64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "f41f8ad9fb06c90289842ff1c03424c7da365a00"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "9f0d17c03ba574413e9882c5fb31479e7609a0ec97e9ca24bf74d62d2d63ba01"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.aarch64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "aarch64"
git-tree-sha1 = "c9eebe05657da7c329fede7ac9e6da9bd707063c"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "675a62bcd1c7960a7b4f65d92157c0b07596cc3528bf6176f28c93eb68c50d31"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.aarch64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5880ad89e7fa2f3044a487ad17e5f27ef70ddc37"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "72e1e6f10c71fdd2dac88e06a004347b0dc3e61d56f798000c6a4f5241a12683"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.armv6l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c2b975ba50e4e64f9365f7e6f1d56af9aa9fa52f"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "fbe00f1fa87fb85e0820e551612e60bd7c70bda8f6fdcbcaad5c3d2b59cf9464"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.armv6l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34a768b82b4dd0fb29e1797de6c606b06e39890f"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "4427f5248b62909886a8dc585e3e0ccf0475a742c09a68edda2f5162135a6f70"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.armv7l-linux-gnueabihf.tar.gz"
[[aws_c_mqtt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45e61aa5193302679c284383c0a169c6730238c9"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "39ff88293351d813139d615b39d13c11dad02d97a8e214ae09d8bac659c2421a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.armv7l-linux-musleabihf.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "6d60c82313e0bf27813eba0cb492279c2f51e357"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "78bdb17a16a46c5f911fef93f56ab91a54bf89655a0ae46e9ea3c49466778e1e"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.i686-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "i686"
git-tree-sha1 = "cefbda735fa7a94b8b8f3e217dbf232c5ae10126"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "c615441b2da215872515baa6902ad52b3e77c8b76e4cad4f8cf7b1ebc282725f"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.i686-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "powerpc64le"
git-tree-sha1 = "03092f6a10c0358b519ba5c8a36fa5fe4db009e0"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "46671abdd63779c79d4e73e42e104cf7422e0f1e9125889a17029f0961243e4a"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.powerpc64le-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "riscv64"
git-tree-sha1 = "759e779fb495aa1c8cd53c8803465de7cde54ba5"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "b838364d286d09e86a527a8cd53f2a11bd5cdba80d9427c9d0ef4a105a54f0be"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.riscv64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "823255be34b89a4fde5926b30237ce2140f18a99"
os = "macos"

    [[aws_c_mqtt.download]]
    sha256 = "1cc72087ce378149d4aef28b9c6f1891685b4d32a006c65849f64aa09fa37f74"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.x86_64-apple-darwin.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "2dcdab533f5ebe72940d458fc09d781d30f4458b"
libc = "glibc"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "198bdf450abf93a5c963a5f76553648d42b57ce94aebb1c4a622540159602a69"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.x86_64-linux-gnu.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "894b383e4bec2b686a620669edf072ced21494d4"
libc = "musl"
os = "linux"

    [[aws_c_mqtt.download]]
    sha256 = "66ba9399d14680bc46ad9823c948c6c4f08f01d866fe6c009bd8c451bbd26d59"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.x86_64-linux-musl.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "80686042fa3257bc149c81b91dca5f382d52b597"
os = "freebsd"

    [[aws_c_mqtt.download]]
    sha256 = "1a96c9fc5fa5b5c5a0ed92cd9409f80cbc805c1f3eee9f2535cdf786cded7422"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.x86_64-unknown-freebsd.tar.gz"
[[aws_c_mqtt]]
arch = "x86_64"
git-tree-sha1 = "fd9d6db9d8adf5f0a27d5227e8e62a1eb0e895b8"
os = "windows"

    [[aws_c_mqtt.download]]
    sha256 = "da2b5b4ab76e482c7cf033660aafab0bf692b3afc7266151be90b2f5ab1a3e57"
    url = "https://github.com/JuliaBinaryWrappers/aws_c_mqtt_jll.jl/releases/download/aws_c_mqtt-v0.13.4+0/aws_c_mqtt.v0.13.4.x86_64-w64-mingw32.tar.gz"
